"use client"
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'

import { ApiProvider } from '@reduxjs/toolkit/query/react'
import { apiSlice } from '@/features/api/apiSlice'

const nunito = Nunito({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} text-gray-900 antialiased`}>
        <ApiProvider api={apiSlice}>{children}</ApiProvider>
      </body>
    </html>
  )
}
